---
# Playbook containing a single play
- name: Setup a webserver.
  hosts: all
  become: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Start service apache2, if not running
      service:
        name: apache2
        enabled: yes
        state: started

    - name: Synchronize content to remote webserver
      synchronize:
        src: writing_playbooks/resources/
        dest: /var/www/html/ 
